#!/bin/bash
md() {
    if [ "$1" == "enter" ]; then
        mamba activate "$2"
    elif [ "$1" == "create" ]; then
        mamba create -n "$2"
    elif [ "$1" == "list" ]; then
        mamba env list
    elif [ "$1" == "delete" ]; then
        mamba env remove -n "$2"
    else
        mamba "${@:1}"
    fi
}
