#!/usr/bin/python3

from rclone_python import rclone
import socket
import schedule
import time
from threading import Lock
import hashlib
from dirhash import dirhash
import os

BACKUP_FOLDERS = ["Desktop", "Documents", "Music", "Obsidian", "Pictures", "Videos"]

class BackerUpper:
    def __init__(self, backup_folders: list[str]):
        self.backup_folders = backup_folders
        self.hostname = socket.gethostname()
        self.last_hash = None
        self.sync_lock = Lock()

        self.filters = []
        for folder in self.backup_folders:
            self.filters.append('--filter')
            self.filters.append(f'"+ /{folder}/**"')
        self.filters.append('--filter')
        self.filters.append('"- *"')

    def home_hash(self, algorithm="sha1", jobs=None):
        combined = hashlib.new(algorithm)
        for folder in self.backup_folders:
            try:
                folder_hash = dirhash(
                    os.path.join('/home/gavin', folder),
                    algorithm,
                    linked_dirs=False,
                    allow_cyclic_links=True,
                    jobs=jobs or os.cpu_count(),
                )
            except (FileNotFoundError, ValueError):
                folder_hash = ""
            combined.update(f"{folder}:{folder_hash}\n".encode())
        return combined.hexdigest()

    def check_changes(self):
        new_hash = self.home_hash()
        if self.last_hash is None:
            self.last_hash = new_hash
            return not rclone.check('/home/gavin', f'discovision:/home/gavin/snapshot/{self.hostname}', args=list(self.filters))[0]
        if new_hash != self.last_hash:
            self.last_hash = new_hash
            return True
        return False

    def sync(self):
        if not self.sync_lock.acquire(blocking=False):
            return

        if not rclone.check_remote_existing('discovision') or not self.check_changes():
            self.sync_lock.release()
            return
        
        rclone.sync('/home/gavin', f'discovision:/home/gavin/snapshot/{self.hostname}', args=self.filters)
        self.sync_lock.release()

if __name__ == "__main__":
    backup = BackerUpper(BACKUP_FOLDERS)
    schedule.every(1).minutes.do(backup.sync)
    while True:
        schedule.run_pending()
        time.sleep(10)