#!/usr/bin/env python3
import subprocess
import time
result = subprocess.run(['plasma-apply-colorscheme', '-l'], stdout=subprocess.PIPE).stdout.decode()
lines = result.split('\n')
current_theme = None
for line in lines:
    if '(current color scheme)' in line:
        current_theme = line.replace('*', '').replace('(current color scheme)', '').replace(' ', '')

if current_theme == 'BreezeLight':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeDark'])
    subprocess.run(['/usr/libexec/plasma-changeicons', 'breeze-dark'])
elif current_theme == 'BreezeDark':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeLight'])
    subprocess.run(['/usr/libexec/plasma-changeicons', 'breeze'])
subprocess.run(['qdbus', 'org.kde.KWin', '/KWin', 'reconfigure'])
subprocess.run(['flatpak', 'kill', 'org.fkoehler.KTailctl'])
subprocess.Popen(['flatpak', 'run', 'org.fkoehler.KTailctl', '>', '/dev/null', '2>&1', '&'])

