[workspace]
authors = ["gandres42 <gandres2416@gmail.com>"]
channels = ["robostack-jazzy", "conda-forge"]
name = "jazzy"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
pip = ">=25.1.1,<26"
nano = ">=8.3,<9"
