#!/bin/bash

# uninstall junk
sudo dnf remove -y akregator dragon elisa-player libreoffice* kaddressbook kamoso kcalc kde-connect kmahjongg kmines kmouth kolourpaint kpat kontact korganizer krdc krfb neochat skanpage qrca kmail

# update packages
sudo dnf check-update
sudo dnf upgrade -y

# enable rpmfusion
sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# install bunk
sudo dnf install -y speedcrunch haruna qt git jetbrains-mono-fonts ffmpeg --allowerasing

# install vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf install code

# install webapp-manager
sudo dnf copr enable -y adriend/fedora-apps
sudo dnf install -y webapp-manager

# install kde-rounded-corners
sudo dnf install -y git cmake gcc-c++ extra-cmake-modules kwin-devel kf6-kconfigwidgets-devel libepoxy-devel kf6-kcmutils-devel kf6-ki18n-devel qt6-qtbase-private-devel wayland-devel libdrm-devel
mkdir -p ~/.local/src && cd ~/.local/src
git clone https://github.com/matinlotfali/KDE-Rounded-Corners.git
cd KDE-Rounded-Corners
mkdir build 
cd build
cmake ..
cmake --build . -j
sudo make install

# install systray mod
cd ~/.local/src
git clone git@github.com:gandres42/systray-mod.git
cd systray-mod && git checkout native
sudo make deps

# setup flathub and install flatpaks
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y md.obsidian.Obsidian \
    org.zotero.Zotero \
    org.onlyoffice.desktopeditors \
    org.jellyfin.JellyfinDesktop \
    org.ferdium.Ferdium \
    io.missioncenter.MissionCenter

# colors
$HOME/.dotfiles/scripts/kde-colors set
cp -r $HOME/.dotfiles/config/konsole $HOME/.local/share

# konsave restore
sudo dnf install -y python3-pip
pip3 install konsave
konsave -i $HOME/.dotfiles/config/klean.knsv
konsave -a klean