#!/bin/bash

# uninstall junk
sudo dnf remove -y akregator dragon elisa-player libreoffice* kaddressbook kamoso kcalc kde-connect kmahjongg kmines kmouth kolourpaint kpat kontact korganizer krdc krfb neochat skanpage qrca kmail firefox

# update packages
sudo dnf check-update
sudo dnf upgrade -y

# enable rpmfusion
sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# install bunk
sudo dnf install -y speedcrunch haruna qt git jetbrains-mono-fonts ffmpeg --allowerasing

# install vscodium
sudo tee -a /etc/yum.repos.d/vscodium.repo << 'EOF'
[gitlab.com_paulcarroty_vscodium_repo]
name=gitlab.com_paulcarroty_vscodium_repo
baseurl=https://paulcarroty.gitlab.io/vscodium-deb-rpm-repo/rpms/
enabled=1
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://gitlab.com/paulcarroty/vscodium-deb-rpm-repo/raw/master/pub.gpg
metadata_expire=1h
EOF
sudo dnf install -y codium

# install webapp-manager
sudo dnf copr enable -y adriend/fedora-apps
sudo dnf install -y webapp-manager

# install nocsd
sudo dnf copr enable -y hazel-bunny/ricing
sudo dnf install -y gtk-nocsd

# install waterfox
sudo dnf copr enable -y deltacopy/waterfox
sudo dnf install -y waterfox

# install rounded corners
sudo dnf copr enable -y matinlotfali/KDE-Rounded-Corners
sudo dnf install -y kwin-effect-roundcorners

# setup flathub and install flatpaks
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y md.obsidian.Obsidian \
    org.zotero.Zotero \
    org.onlyoffice.desktopeditors \
    org.jellyfin.JellyfinDesktop \
    org.ferdium.Ferdium \
    io.missioncenter.MissionCenter

# colors
$HOME/.dotfiles/scripts/kde-colors set
cp -r $HOME/.dotfiles/config/konsole $HOME/.local/share

# konsave restore
sudo dnf install -y python3-pip
pip3 install konsave
konsave -i $HOME/.dotfiles/config/klean.knsv
konsave -a klean