#!/bin/bash

# uninstall junk
sudo dnf remove -y akregator dragon elisa-player libreoffice* kaddressbook kamoso kcalc kde-connect kmahjongg kmines kmouth kolourpaint kpat kontact korganizer krdc krfb neochat skanpage qrca kmail

# update packages
sudo dnf check-update
sudo dnf upgrade -y

# enable rpmfusion
sudo dnf install -y https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

# install bunk
sudo dnf install -y speedcrunch haruna qt git jetbrains-mono-fonts ffmpeg --allowerasing

# install vscode
sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc &&
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf install -y code

# install webapp-manager
sudo dnf copr enable -y adriend/fedora-apps
sudo dnf install -y webapp-manager

# clone utils
mkdir -p $HOME/Utilities
cd $HOME/Utilities
git clone https://github.com/matinlotfali/KDE-Rounded-Corners.git
git clone git@github.com:gandres42/systray-mod.git
git clone https://github.com/dhruv8sh/kara.git

# setup flathub and install flatpaks
sudo flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install -y \
    md.obsidian.Obsidian \
    org.zotero.Zotero \
    org.onlyoffice.desktopeditors \
    org.jellyfin.JellyfinDesktop \
    org.ferdium.Ferdium

# install appman
cd $HOME/.dotfiles/config
wget -q https://raw.githubusercontent.com/ivan-hc/AM/main/AM-INSTALLER
chmod a+x ./AM-INSTALLER
./AM-INSTALLER -i appman
appman_location="$HOME/.applications" appman -v
rm AM-INSTALLER

# install deezer-enhanced
appman install deezer-enhanced
mkdir -p $HOME/.config/deezer-enhanced
ln -s $HOME/.dotfiles/config/deezer.css $HOME/.config/deezer-enhanced/style.css
mkdir -p $HOME/.config/deezer-enhanced/assets
wget -O $HOME/.config/deezer-enhanced/assets/icon.png https://cdn.jsdelivr.net/gh/homarr-labs/dashboard-icons/png/deezer.png

# install foxglove-studio
curl -fsSL https://raw.githubusercontent.com/89luca89/distrobox/main/install | sh -s -- --v2
distrobox create -i osrf/ros:lyrical-desktop-full lyrical
wget https://get.foxglove.dev/desktop/latest/foxglove-studio-latest-linux-amd64.deb
distrobox enter lyrical --exec sudo apt update
distrobox enter lyrical --exec sudo apt upgrade -y
distrobox enter lyrical --exec sudo apt install -y $HOME/.dotfiles/config/foxglove-studio-latest-linux-amd64.deb
distrobox enter lyrical --exec distrobox-export --app foxglove-studio
rm $HOME/.dotfiles/config/foxglove-studio-latest-linux-amd64.deb

# colors
$HOME/.dotfiles/scripts/kde-colors set
cp -r $HOME/.dotfiles/config/konsole $HOME/.local/share

# konsave restore
sudo dnf install -y python3-pip
pip3 install konsave
konsave -i $HOME/.dotfiles/config/klean.knsv
konsave -a klean

# backups
pip install rclone-python
mkdir -p ~/.config/systemd/user
ln -sf ~/.dotfiles/backup/rcloned.service ~/.config/systemd/user/rcloned.service
systemctl --user daemon-reload
systemctl --user enable --now rcloned.service
