#!/bin/bash
if [ "$1" = "set" ]; then
    rm $HOME/.local/share/color-schemes/*
    rsync -aP --ignore-existing ./config/color-schemes/ $HOME/.local/share/color-schemes
    cp ./config/kwinrulesrc ~/.config
    qdbus org.kde.KWin /KWin reconfigure
elif [ "$1" = "copy" ]; then
    cp -r $HOME/.local/share/color-schemes ./config
    cp ~/.config/kwinrulesrc ./config/kwinrulesrc
else
    echo "usage: plasma-colors <copy | set>"
fi
