#!/bin/bash

# config
OWNER="lichtblick-suite"
REPO="lichtblick"
BIN="lichtblick"

# download and unzip latest version
cd $HOME/.local/src
url=$(curl -s "https://api.github.com/repos/$OWNER/$REPO/releases/latest" \
  | grep browser_download_url \
  | grep linux-x64.tar.gz \
  | cut -d '"' -f 4)
filename=$(basename "$url")
dirname="${filename%.tar.gz}"
wget "$url" && tar -xvf $filename
rm $filename

# symlink bin into .local/bin
ln -sf $PWD/$dirname/$BIN $HOME/.local/bin/$BIN

# create desktop file
url=$(curl -s "https://api.github.com/users/$OWNER" \
  | grep -Eo '"avatar_url": *"[^"]+"' \
  | cut -d'"' -f4)

wget -O $HOME/.local/share/icons/$BIN.png "$url"

echo \
"[Desktop Entry]
Name=Lichtblick
Exec=lichtblick --ozone-platform=x11 %U
Terminal=false
Type=Application
Icon=$HOME/.local/share/icons/$BIN.png
StartupWMClass=Lichtblick
Categories=Network;
Comment=Robotics visualization" \
> $HOME/.local/share/applications/$BIN.desktop

update-desktop-database $HOME/.local/share/applications