#!/bin/bash
if [ "$1" = "deploy" ]; then
    rsync -aP --ignore-existing ./config/color-schemes/ $HOME/.local/share/color-schemes
    cp ./config/kwinrulesrc ~/.config
    qdbus org.kde.KWin /KWin reconfigure
elif [ "$1" = "copy" ]; then
    cp -r $HOME/.local/share/color-schemes ./config
    cp ~/.config/kwinrulesrc ./config/kwinrulesrc
else
    echo "usage: plasmoid-config <copy | deploy>"
fi
