#!/bin/bash
# flatpak install --user com.mastermindzh.tidal-hifi
cd /tmp
url=$(curl -s "https://api.github.com/repos/jxnxsdev/TidaLuna-Installer/releases/latest" \
  | grep browser_download_url \
  | grep linux-x86_64.tar.gz \
  | cut -d '"' -f 4)
filename=$(basename "$url")
dirname="${filename%.tar.gz}"
wget -q "$url" && tar -xf $filename
rm $filename
echo "/home/gavin/.local/share/flatpak/app/com.mastermindzh.tidal-hifi/current/active/files/lib/tidal-hifi/resources"

cleanup() {
  rm -f /tmp/luna-installer
}
trap cleanup EXIT
/tmp/luna-installer
