#!/bin/bash
exec 9>/tmp/discosync.lock || exit 1
flock -n 9 || exit 0

folders=("Desktop" "Documents" "Music" "Obsidian" "Pictures" "Videos")

cmd="rclone sync $HOME discovision:/home/gavin/snapshot/$HOSTNAME" # --filter \"- **/.directory\""
for s in "${folders[@]}"; do
  cmd+=" --filter \"+ /$s/**\""
done
cmd+=" --filter \"- *\" --progress"
eval "$cmd"
