#!/bin/bash

# Check if the Distrobox name is provided as a parameter
if [ -z "$1" ]; then
  echo "Usage: $0 <distrobox_name>"
  exit 1
fi

DISTROBOX_NAME="$1"
OUTPUT_DIR="${HOME}/.config/Code/User/globalStorage/ms-vscode-remote.remote-containers/nameConfigs"
OUTPUT_FILE="${OUTPUT_DIR}/${DISTROBOX_NAME}.json"

# Create the output directory if it doesn't exist
mkdir -p "$OUTPUT_DIR"

# Create the JSON file with the required contents
cat <<EOF > "$OUTPUT_FILE"
{
  "name": "$DISTROBOX_NAME",
  "remoteUser": "\${localEnv:USER}",
  "settings": {
    "remote.containers.copyGitConfig": false,
    "remote.containers.gitCredentialHelperConfigLocation": "none",
    "terminal.integrated.profiles.linux": {
      "shell": {
        "path": "\${localEnv:SHELL}",
        "args": [
          "-l"
        ]
      }
    },
    "terminal.integrated.defaultProfile.linux": "shell"
  },
  "remoteEnv": {
    "COLORTERM": "\${localEnv:COLORTERM}",
    "DBUS_SESSION_BUS_ADDRESS": "\${localEnv:DBUS_SESSION_BUS_ADDRESS}",
    "DESKTOP_SESSION": "\${localEnv:DESKTOP_SESSION}",
    "DISPLAY": "\${localEnv:DISPLAY}",
    "LANG": "\${localEnv:LANG}",
    "SHELL": "\${localEnv:SHELL}",
    "SSH_AUTH_SOCK": "\${localEnv:SSH_AUTH_SOCK}",
    "TERM": "\${localEnv:TERM}",
    "VTE_VERSION": "\${localEnv:VTE_VERSION}",
    "XDG_CURRENT_DESKTOP": "\${localEnv:XDG_CURRENT_DESKTOP}",
    "XDG_DATA_DIRS": "\${localEnv:XDG_DATA_DIRS}",
    "XDG_MENU_PREFIX": "\${localEnv:XDG_MENU_PREFIX}",
    "XDG_RUNTIME_DIR": "\${localEnv:XDG_RUNTIME_DIR}",
    "XDG_SESSION_DESKTOP": "\${localEnv:XDG_SESSION_DESKTOP}",
    "XDG_SESSION_TYPE": "\${localEnv:XDG_SESSION_TYPE}",
    "QT_AUTO_SCREEN_SCALE_FACTOR": "0",
    "CONTAINER_ID":  "$DISTROBOX_NAME"
  }
}
EOF

# echo "$OUTPUT_FILE has been created with the specified contents for Distrobox name '$DISTROBOX_NAME'."
