#!/bin/bash

# rounded corners
cd ~/.local/src/KDE-Rounded-Corners
git pull
rm -rf build
mkdir build
cd build
cmake ..
cmake --build . -j
sudo make install

# systray icons
cd ~/.local/src/systray-mod
make
sudo make install