#!/usr/bin/env python3
import re
import subprocess

def replace_decocolor(old_value: str, new_value: str, file_path: str) -> None:
    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    updated = re.sub(
        rf"^decocolor={re.escape(old_value)}$",
        f"decocolor={new_value}",
        content,
        flags=re.MULTILINE,
    )

    if updated != content:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(updated)

current_theme = subprocess.run("kreadconfig5 --key LookAndFeelPackage", stdout=subprocess.PIPE, shell=True).stdout.decode()
kwinrulesrc = "/home/gavin/.config/kwinrulesrc"
if "org.kde.breezetwilight.desktop" in current_theme:
    subprocess.run("lookandfeeltool -a org.kde.breezedark.desktop", stdout=subprocess.PIPE, shell=True)
    # replace_decocolor("LibadwaitaLight", "LibadwaitaDark", kwinrulesrc)
elif "org.kde.breezedark.desktop" in current_theme:
    subprocess.run("lookandfeeltool -a org.kde.breezetwilight.desktop", stdout=subprocess.PIPE, shell=True)
    # replace_decocolor("LibadwaitaDark", "LibadwaitaLight", kwinrulesrc)
# subprocess.run(["qdbus", "org.kde.KWin", "/KWin", "reconfigure"], check=False)
