#!/usr/bin/env python3
import subprocess
import time
result = subprocess.run(['plasma-apply-colorscheme', '-l'], stdout=subprocess.PIPE).stdout.decode()
lines = result.split('\n')
current_theme = None
for line in lines:
    if '(current color scheme)' in line:
        current_theme = line.replace('*', '').replace('(current color scheme)', '').replace(' ', '')

if current_theme == 'BreezeLighter':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeDarker'])
    subprocess.run(['/usr/libexec/plasma-changeicons', 'breeze-dark'])
    # subprocess.run(['sed', '-i', "'s/^decocolor=Brave$/decocolor=BraveDark/'", '/home/gavin/.config/kwinrulesrc'])
    # subprocess.run(['sed', '-i', 's/^decocolor=Brave$/decocolor=BraveDark/', '/home/gavin/.config/kwinrulesrc'])

elif current_theme == 'BreezeDarker':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeLighter'])
    subprocess.run(['/usr/libexec/plasma-changeicons', 'breeze'])
    # subprocess.run(['sed', '-i', "'s/^decocolor=BraveDark$/decocolor=Brave/'", '/home/gavin/.config/kwinrulesrc'])
    # subprocess.run(['sed', '-i', 's/^decocolor=BraveDark$/decocolor=Brave/', '/home/gavin/.config/kwinrulesrc'])

# subprocess.run(['qdbus', 'org.kde.KWin', '/KWin', 'reconfigure'])
