#!/bin/bash
if [ $# -lt 4 ]; then
    echo "Usage: video-trim <input> <start_time> <end_time> <output>"
    echo "Example: video-trim video.mp4 00:01:30 00:02:45 trimmed.mp4"
    exit 1
fi

input="$1"
start="$2"
end="$3"
output="$4"

ffmpeg -i "$input" -ss "$start" -to "$end" -c copy "$output"