#!/usr/bin/env python3
import subprocess
result = subprocess.run(['plasma-apply-colorscheme', '-l'], stdout=subprocess.PIPE).stdout.decode()
lines = result.split('\n')
current_theme = None
for line in lines:
    if '(current color scheme)' in line:
        current_theme = line.replace('*', '').replace('(current color scheme)', '').replace(' ', '')
if current_theme == 'BreezeLight':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeDark'])
elif current_theme == 'BreezeDark':
    subprocess.run(['plasma-apply-colorscheme', 'BreezeLight'])